execution:
    uuid: 6086dde0-12c0-47f8-9e16-42d8c21230de
    runtime:
        start: 2023-03-21T12:15:22.767890-07:00
        end: 2023-03-21T12:15:23.410605-07:00
        duration: 642715 microseconds

action:
    type: pipeline
    plugin: !ref 'environment:plugins:diversity'
    action: alpha
    inputs:
    -   table: 4bb5eec9-2444-4ae7-97ff-d97dbdfab0c1
    parameters:
    -   metric: shannon
    output-name: alpha_diversity
    alias-of: 8b3e2cb4-f1aa-41d7-b8f9-7122b0247d8d

environment:
    platform: linux-x86_64
    python: |-
        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
        [GCC 10.3.0]
    framework:
        version: 2022.8.3
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2022.8.3|0'
    plugins:
        diversity:
            version: 2022.8.0
            website: https://github.com/qiime2/q2-diversity
    python-packages:
        certifi: 2022.12.7
        qiime2: 2022.8.3
        q2galaxy: 2022.8.1
        q2-feature-table: 2022.8.1
        q2templates: 2022.8.0
        q2-mystery-stew: 2022.8.0
        q2cli: 2022.8.0
        q2-types: 2022.8.0
        q2-alignment: 2022.8.0
        q2-composition: 2022.8.0
        q2-cutadapt: 2022.8.0
        q2-deblur: 2022.8.0
        q2-demux: 2022.8.0
        q2-emperor: 2022.8.0
        q2-fragment-insertion: 2022.8.0
        q2-gneiss: 2022.8.0
        q2-metadata: 2022.8.0
        q2-quality-filter: 2022.8.0
        q2-taxa: 2022.8.0
        q2-diversity-lib: 2022.8.0
        q2-phylogeny: 2022.8.0
        q2-quality-control: 2022.8.0
        q2-sample-classifier: 2022.8.0
        q2-vsearch: 2022.8.0
        q2-diversity: 2022.8.0
        q2-feature-classifier: 2022.8.0
        q2-longitudinal: 2022.8.0
        q2-dada2: 2022.8.0
        pytz: 2022.2.1
        setuptools: 65.3.0
        cryptography: 37.0.4
        pyzmq: 24.0.1
        pip: 22.3.1
        attrs: 22.1.0
        pyOpenSSL: 22.0.0
        packaging: '21.3'
        argon2-cffi: 21.3.0
        argon2-cffi-bindings: 21.2.0
        isoduration: 20.11.0
        cplex: 20.1.0.0
        unicodedata2: 14.0.0
        PyQt5-sip: 12.11.0
        rich: 12.6.0
        Pillow: 9.2.0
        ipython: 8.5.0
        natsort: 8.2.0
        click: 8.1.3
        ipywidgets: 8.0.2
        jupyter-client: 7.4.8
        nbconvert: 7.2.6
        pytest: 7.1.3
        flufl.lock: '7.1'
        ipykernel: 6.15.2
        sip: 6.6.2
        notebook: 6.5.2
        tornado: '6.2'
        hyperframe: 6.0.1
        PyYAML: '6.0'
        python-libsbml: 5.19.2
        PyQt5: 5.15.7
        psutil: 5.9.2
        importlib-resources: 5.9.0
        traitlets: 5.7.1
        nbformat: 5.4.0
        diskcache: 5.4.0
        jupyter-core: 5.1.0
        swiglpk: 5.0.8
        bleach: 5.0.1
        tqdm: 4.64.1
        fonttools: 4.37.1
        jsonschema: 4.15.0
        importlib-metadata: 4.11.4
        beautifulsoup4: 4.11.1
        lxml: 4.9.1
        pexpect: 4.8.0
        DendroPy: 4.5.2
        decorator: 4.4.2
        sepp: 4.3.10
        typing-extensions: 4.3.0
        cutadapt: '4.1'
        h2: 4.1.0
        widgetsnbextension: 4.0.3
        hpack: 4.0.0
        lz4: 4.0.0
        ply: '3.11'
        zipp: 3.8.1
        anyio: 3.6.2
        matplotlib: 3.5.3
        jupyterlab: 3.5.1
        idna: '3.3'
        palettable: 3.3.0
        ijson: 3.1.3
        Jinja2: 3.1.2
        threadpoolctl: 3.1.0
        prompt-toolkit: 3.0.31
        pyparsing: 3.0.9
        jupyterlab-widgets: 3.0.3
        atpublic: 3.0.1
        requests: 2.28.1
        pycparser: '2.21'
        jupyterlab-server: 2.16.5
        fastjsonschema: 2.16.1
        Pygments: 2.13.0
        Babel: 2.11.0
        h5py: 2.10.0
        networkx: 2.8.6
        python-dateutil: 2.8.2
        platformdirs: 2.6.0
        bokeh: 2.4.3
        soupsieve: 2.3.2.post1
        jsonpointer: '2.3'
        biom-format: 2.1.12
        gmpy2: 2.1.2
        charset-normalizer: 2.1.1
        MarkupSafe: 2.1.1
        tzlocal: '2.1'
        asttokens: 2.0.8
        mistune: 2.0.4
        python-json-logger: 2.0.4
        tomli: 2.0.1
        jupyter-server: 2.0.1
        urllib3: 1.26.11
        numpy: 1.23.2
        six: 1.16.0
        cffi: 1.15.1
        webcolors: '1.12'
        sympy: 1.11.1
        py: 1.11.0
        pydantic: 1.10.2
        scipy: 1.8.1
        Send2Trash: 1.8.0
        PySocks: 1.7.1
        depinfo: 1.7.0
        backports.functools-lru-cache: 1.6.4
        debugpy: 1.6.3
        optlang: 1.6.1
        xopen: 1.6.0
        nest-asyncio: 1.5.5
        fqdn: 1.5.1
        rfc3986: 1.5.0
        pandocfilters: 1.5.0
        pandas: 1.4.4
        kiwisolver: 1.4.4
        appdirs: 1.4.4
        websocket-client: 1.4.2
        pkgutil-resolve-name: 1.3.10
        nose: 1.3.7
        bibtexparser: 1.3.0
        sniffio: 1.3.0
        fastcluster: 1.2.6
        arrow: 1.2.3
        mpmath: 1.2.1
        tinycss2: 1.2.1
        joblib: 1.2.0
        scikit-learn: 1.2.0
        uri-template: 1.2.0
        munkres: 1.1.4
        iniconfig: 1.1.1
        deblur: 1.1.1
        iow: 1.0.5
        msgpack: 1.0.4
        emperor: 1.0.3
        isal: 1.0.1
        executing: 1.0.0
        pluggy: 1.0.0
        unifrac: 1.0.0
        numba: 0.53.1
        wheel: 0.37.1
        llvmlite: 0.36.0
        micom: 0.32.2
        Cython: 0.29.32
        httpx: 0.23.1
        cobra: 0.23.0
        future: 0.18.2
        pyrsistent: 0.18.1
        jedi: 0.18.1
        ruamel.yaml: 0.17.21
        terminado: 0.17.1
        httpcore: 0.16.2
        prometheus-client: 0.15.0
        hdmedians: 0.14.2
        h11: 0.14.0
        statsmodels: 0.13.2
        CacheControl: 0.12.11
        lockfile: 0.12.2
        q2-micom: 0.12.1
        seaborn: 0.12.0
        cycler: 0.11.0
        toml: 0.10.2
        plotnine: 0.10.1
        json5: 0.9.10
        symengine: 0.9.2
        dnaio: 0.9.1
        commonmark: 0.9.1
        parso: 0.8.3
        mizani: 0.8.1
        dataclasses: '0.8'
        pickleshare: 0.7.5
        nbclient: 0.7.2
        defusedxml: 0.7.1
        ptyprocess: 0.7.0
        brotlipy: 0.7.0
        osqp: 0.6.2.post8
        pynndescent: 0.5.7
        scikit-bio: 0.5.7
        umap-learn: 0.5.3
        patsy: 0.5.2
        webencodings: 0.5.1
        stack-data: 0.5.0
        jupyter-events: 0.5.0
        nbclassic: 0.4.8
        gneiss: 0.4.6
        colorama: 0.4.5
        jupyter-server-terminals: 0.4.2
        entrypoints: '0.4'
        dill: 0.3.5.1
        ruamel.yaml.clib: 0.2.7
        wcwidth: 0.2.5
        pure-eval: 0.2.2
        jupyterlab-pygments: 0.2.2
        notebook-shim: 0.2.2
        backports.zoneinfo: 0.2.1
        backcall: 0.2.0
        ipython-genutils: 0.2.0
        matplotlib-inline: 0.1.6
        qdldl: 0.1.5.post2
        rfc3339-validator: 0.1.4
        rfc3986-validator: 0.1.1
